version: 0.2

env:
  variables:
    AWS_REGION: eu-west-2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 577638398727.dkr.ecr.eu-west-2.amazonaws.com

  build:
    commands:
      - echo Building frontend...
      - docker build -t frontend ./frontend
      - docker tag frontend:latest 577638398727.dkr.ecr.eu-west-2.amazonaws.com/frontend:latest

  post_build:
    commands:
      - echo Pushing frontend image...
      - docker push 577638398727.dkr.ecr.eu-west-2.amazonaws.com/frontend:latest

      - echo Generating imagedefinitions files...
      - |
        echo '[{"name":"frontend","imageUri":"577638398727.dkr.ecr.eu-west-2.amazonaws.com/frontend:latest"}]' > frontend-imagedefinitions.json
 
artifacts:
  files:
    - frontend-imagedefinitions.json
